// Code generated by ent, DO NOT EDIT.

package providerordertokenaddress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/paycrest/paycrest-protocol/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldLTE(FieldID, id))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEQ(FieldAddress, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v Network) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v Network) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...Network) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...Network) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNotIn(FieldNetwork, vs...))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(sql.FieldContainsFold(FieldAddress, v))
}

// HasProviderordertoken applies the HasEdge predicate on the "providerordertoken" edge.
func HasProviderordertoken() predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderordertokenTable, ProviderordertokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderordertokenWith applies the HasEdge predicate on the "providerordertoken" edge with a given conditions (other predicates).
func HasProviderordertokenWith(preds ...predicate.ProviderOrderToken) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(func(s *sql.Selector) {
		step := newProviderordertokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderOrderTokenAddress) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderOrderTokenAddress) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderOrderTokenAddress) predicate.ProviderOrderTokenAddress {
	return predicate.ProviderOrderTokenAddress(func(s *sql.Selector) {
		p(s.Not())
	})
}
