// Code generated by ent, DO NOT EDIT.

package receiveaddress

import (
	"entgo.io/ent/dialect/sql"
	"github.com/paycrest/paycrest-protocol/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLTE(FieldID, id))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldAddress, v))
}

// AccountIndex applies equality check predicate on the "accountIndex" field. It's identical to AccountIndexEQ.
func AccountIndex(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldAccountIndex, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldContainsFold(FieldAddress, v))
}

// AccountIndexEQ applies the EQ predicate on the "accountIndex" field.
func AccountIndexEQ(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldAccountIndex, v))
}

// AccountIndexNEQ applies the NEQ predicate on the "accountIndex" field.
func AccountIndexNEQ(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNEQ(FieldAccountIndex, v))
}

// AccountIndexIn applies the In predicate on the "accountIndex" field.
func AccountIndexIn(vs ...int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldIn(FieldAccountIndex, vs...))
}

// AccountIndexNotIn applies the NotIn predicate on the "accountIndex" field.
func AccountIndexNotIn(vs ...int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNotIn(FieldAccountIndex, vs...))
}

// AccountIndexGT applies the GT predicate on the "accountIndex" field.
func AccountIndexGT(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGT(FieldAccountIndex, v))
}

// AccountIndexGTE applies the GTE predicate on the "accountIndex" field.
func AccountIndexGTE(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldGTE(FieldAccountIndex, v))
}

// AccountIndexLT applies the LT predicate on the "accountIndex" field.
func AccountIndexLT(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLT(FieldAccountIndex, v))
}

// AccountIndexLTE applies the LTE predicate on the "accountIndex" field.
func AccountIndexLTE(v int) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldLTE(FieldAccountIndex, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReceiveAddress) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReceiveAddress) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReceiveAddress) predicate.ReceiveAddress {
	return predicate.ReceiveAddress(func(s *sql.Selector) {
		p(s.Not())
	})
}
