// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/paycrest-protocol/ent/predicate"
	"github.com/paycrest/paycrest-protocol/ent/provideravailability"
	"github.com/paycrest/paycrest-protocol/ent/providerprofile"
)

// ProviderAvailabilityQuery is the builder for querying ProviderAvailability entities.
type ProviderAvailabilityQuery struct {
	config
	ctx          *QueryContext
	order        []provideravailability.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProviderAvailability
	withProvider *ProviderProfileQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderAvailabilityQuery builder.
func (paq *ProviderAvailabilityQuery) Where(ps ...predicate.ProviderAvailability) *ProviderAvailabilityQuery {
	paq.predicates = append(paq.predicates, ps...)
	return paq
}

// Limit the number of records to be returned by this query.
func (paq *ProviderAvailabilityQuery) Limit(limit int) *ProviderAvailabilityQuery {
	paq.ctx.Limit = &limit
	return paq
}

// Offset to start from.
func (paq *ProviderAvailabilityQuery) Offset(offset int) *ProviderAvailabilityQuery {
	paq.ctx.Offset = &offset
	return paq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (paq *ProviderAvailabilityQuery) Unique(unique bool) *ProviderAvailabilityQuery {
	paq.ctx.Unique = &unique
	return paq
}

// Order specifies how the records should be ordered.
func (paq *ProviderAvailabilityQuery) Order(o ...provideravailability.OrderOption) *ProviderAvailabilityQuery {
	paq.order = append(paq.order, o...)
	return paq
}

// QueryProvider chains the current query on the "provider" edge.
func (paq *ProviderAvailabilityQuery) QueryProvider() *ProviderProfileQuery {
	query := (&ProviderProfileClient{config: paq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := paq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := paq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(provideravailability.Table, provideravailability.FieldID, selector),
			sqlgraph.To(providerprofile.Table, providerprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, provideravailability.ProviderTable, provideravailability.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(paq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderAvailability entity from the query.
// Returns a *NotFoundError when no ProviderAvailability was found.
func (paq *ProviderAvailabilityQuery) First(ctx context.Context) (*ProviderAvailability, error) {
	nodes, err := paq.Limit(1).All(setContextOp(ctx, paq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{provideravailability.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) FirstX(ctx context.Context) *ProviderAvailability {
	node, err := paq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProviderAvailability ID from the query.
// Returns a *NotFoundError when no ProviderAvailability ID was found.
func (paq *ProviderAvailabilityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = paq.Limit(1).IDs(setContextOp(ctx, paq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{provideravailability.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) FirstIDX(ctx context.Context) int {
	id, err := paq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProviderAvailability entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderAvailability entity is found.
// Returns a *NotFoundError when no ProviderAvailability entities are found.
func (paq *ProviderAvailabilityQuery) Only(ctx context.Context) (*ProviderAvailability, error) {
	nodes, err := paq.Limit(2).All(setContextOp(ctx, paq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{provideravailability.Label}
	default:
		return nil, &NotSingularError{provideravailability.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) OnlyX(ctx context.Context) *ProviderAvailability {
	node, err := paq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProviderAvailability ID in the query.
// Returns a *NotSingularError when more than one ProviderAvailability ID is found.
// Returns a *NotFoundError when no entities are found.
func (paq *ProviderAvailabilityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = paq.Limit(2).IDs(setContextOp(ctx, paq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{provideravailability.Label}
	default:
		err = &NotSingularError{provideravailability.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) OnlyIDX(ctx context.Context) int {
	id, err := paq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProviderAvailabilities.
func (paq *ProviderAvailabilityQuery) All(ctx context.Context) ([]*ProviderAvailability, error) {
	ctx = setContextOp(ctx, paq.ctx, "All")
	if err := paq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderAvailability, *ProviderAvailabilityQuery]()
	return withInterceptors[[]*ProviderAvailability](ctx, paq, qr, paq.inters)
}

// AllX is like All, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) AllX(ctx context.Context) []*ProviderAvailability {
	nodes, err := paq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProviderAvailability IDs.
func (paq *ProviderAvailabilityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if paq.ctx.Unique == nil && paq.path != nil {
		paq.Unique(true)
	}
	ctx = setContextOp(ctx, paq.ctx, "IDs")
	if err = paq.Select(provideravailability.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) IDsX(ctx context.Context) []int {
	ids, err := paq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (paq *ProviderAvailabilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, paq.ctx, "Count")
	if err := paq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, paq, querierCount[*ProviderAvailabilityQuery](), paq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) CountX(ctx context.Context) int {
	count, err := paq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (paq *ProviderAvailabilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, paq.ctx, "Exist")
	switch _, err := paq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (paq *ProviderAvailabilityQuery) ExistX(ctx context.Context) bool {
	exist, err := paq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderAvailabilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (paq *ProviderAvailabilityQuery) Clone() *ProviderAvailabilityQuery {
	if paq == nil {
		return nil
	}
	return &ProviderAvailabilityQuery{
		config:       paq.config,
		ctx:          paq.ctx.Clone(),
		order:        append([]provideravailability.OrderOption{}, paq.order...),
		inters:       append([]Interceptor{}, paq.inters...),
		predicates:   append([]predicate.ProviderAvailability{}, paq.predicates...),
		withProvider: paq.withProvider.Clone(),
		// clone intermediate query.
		sql:  paq.sql.Clone(),
		path: paq.path,
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (paq *ProviderAvailabilityQuery) WithProvider(opts ...func(*ProviderProfileQuery)) *ProviderAvailabilityQuery {
	query := (&ProviderProfileClient{config: paq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	paq.withProvider = query
	return paq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Cadence provideravailability.Cadence `json:"cadence,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderAvailability.Query().
//		GroupBy(provideravailability.FieldCadence).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (paq *ProviderAvailabilityQuery) GroupBy(field string, fields ...string) *ProviderAvailabilityGroupBy {
	paq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderAvailabilityGroupBy{build: paq}
	grbuild.flds = &paq.ctx.Fields
	grbuild.label = provideravailability.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Cadence provideravailability.Cadence `json:"cadence,omitempty"`
//	}
//
//	client.ProviderAvailability.Query().
//		Select(provideravailability.FieldCadence).
//		Scan(ctx, &v)
func (paq *ProviderAvailabilityQuery) Select(fields ...string) *ProviderAvailabilitySelect {
	paq.ctx.Fields = append(paq.ctx.Fields, fields...)
	sbuild := &ProviderAvailabilitySelect{ProviderAvailabilityQuery: paq}
	sbuild.label = provideravailability.Label
	sbuild.flds, sbuild.scan = &paq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderAvailabilitySelect configured with the given aggregations.
func (paq *ProviderAvailabilityQuery) Aggregate(fns ...AggregateFunc) *ProviderAvailabilitySelect {
	return paq.Select().Aggregate(fns...)
}

func (paq *ProviderAvailabilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range paq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, paq); err != nil {
				return err
			}
		}
	}
	for _, f := range paq.ctx.Fields {
		if !provideravailability.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if paq.path != nil {
		prev, err := paq.path(ctx)
		if err != nil {
			return err
		}
		paq.sql = prev
	}
	return nil
}

func (paq *ProviderAvailabilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderAvailability, error) {
	var (
		nodes       = []*ProviderAvailability{}
		withFKs     = paq.withFKs
		_spec       = paq.querySpec()
		loadedTypes = [1]bool{
			paq.withProvider != nil,
		}
	)
	if paq.withProvider != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, provideravailability.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderAvailability).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderAvailability{config: paq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, paq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := paq.withProvider; query != nil {
		if err := paq.loadProvider(ctx, query, nodes, nil,
			func(n *ProviderAvailability, e *ProviderProfile) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (paq *ProviderAvailabilityQuery) loadProvider(ctx context.Context, query *ProviderProfileQuery, nodes []*ProviderAvailability, init func(*ProviderAvailability), assign func(*ProviderAvailability, *ProviderProfile)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ProviderAvailability)
	for i := range nodes {
		if nodes[i].provider_profile_availability == nil {
			continue
		}
		fk := *nodes[i].provider_profile_availability
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(providerprofile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_profile_availability" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (paq *ProviderAvailabilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := paq.querySpec()
	_spec.Node.Columns = paq.ctx.Fields
	if len(paq.ctx.Fields) > 0 {
		_spec.Unique = paq.ctx.Unique != nil && *paq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, paq.driver, _spec)
}

func (paq *ProviderAvailabilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(provideravailability.Table, provideravailability.Columns, sqlgraph.NewFieldSpec(provideravailability.FieldID, field.TypeInt))
	_spec.From = paq.sql
	if unique := paq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if paq.path != nil {
		_spec.Unique = true
	}
	if fields := paq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provideravailability.FieldID)
		for i := range fields {
			if fields[i] != provideravailability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := paq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := paq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := paq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := paq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (paq *ProviderAvailabilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(paq.driver.Dialect())
	t1 := builder.Table(provideravailability.Table)
	columns := paq.ctx.Fields
	if len(columns) == 0 {
		columns = provideravailability.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if paq.sql != nil {
		selector = paq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if paq.ctx.Unique != nil && *paq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range paq.predicates {
		p(selector)
	}
	for _, p := range paq.order {
		p(selector)
	}
	if offset := paq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := paq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProviderAvailabilityGroupBy is the group-by builder for ProviderAvailability entities.
type ProviderAvailabilityGroupBy struct {
	selector
	build *ProviderAvailabilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pagb *ProviderAvailabilityGroupBy) Aggregate(fns ...AggregateFunc) *ProviderAvailabilityGroupBy {
	pagb.fns = append(pagb.fns, fns...)
	return pagb
}

// Scan applies the selector query and scans the result into the given value.
func (pagb *ProviderAvailabilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pagb.build.ctx, "GroupBy")
	if err := pagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderAvailabilityQuery, *ProviderAvailabilityGroupBy](ctx, pagb.build, pagb, pagb.build.inters, v)
}

func (pagb *ProviderAvailabilityGroupBy) sqlScan(ctx context.Context, root *ProviderAvailabilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pagb.fns))
	for _, fn := range pagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pagb.flds)+len(pagb.fns))
		for _, f := range *pagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderAvailabilitySelect is the builder for selecting fields of ProviderAvailability entities.
type ProviderAvailabilitySelect struct {
	*ProviderAvailabilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pas *ProviderAvailabilitySelect) Aggregate(fns ...AggregateFunc) *ProviderAvailabilitySelect {
	pas.fns = append(pas.fns, fns...)
	return pas
}

// Scan applies the selector query and scans the result into the given value.
func (pas *ProviderAvailabilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pas.ctx, "Select")
	if err := pas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderAvailabilityQuery, *ProviderAvailabilitySelect](ctx, pas.ProviderAvailabilityQuery, pas, pas.inters, v)
}

func (pas *ProviderAvailabilitySelect) sqlScan(ctx context.Context, root *ProviderAvailabilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pas.fns))
	for _, fn := range pas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
