// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/paycrest-protocol/ent/receiveaddress"
)

// ReceiveAddressCreate is the builder for creating a ReceiveAddress entity.
type ReceiveAddressCreate struct {
	config
	mutation *ReceiveAddressMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rac *ReceiveAddressCreate) SetCreatedAt(t time.Time) *ReceiveAddressCreate {
	rac.mutation.SetCreatedAt(t)
	return rac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rac *ReceiveAddressCreate) SetNillableCreatedAt(t *time.Time) *ReceiveAddressCreate {
	if t != nil {
		rac.SetCreatedAt(*t)
	}
	return rac
}

// SetUpdatedAt sets the "updated_at" field.
func (rac *ReceiveAddressCreate) SetUpdatedAt(t time.Time) *ReceiveAddressCreate {
	rac.mutation.SetUpdatedAt(t)
	return rac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rac *ReceiveAddressCreate) SetNillableUpdatedAt(t *time.Time) *ReceiveAddressCreate {
	if t != nil {
		rac.SetUpdatedAt(*t)
	}
	return rac
}

// SetAddress sets the "address" field.
func (rac *ReceiveAddressCreate) SetAddress(s string) *ReceiveAddressCreate {
	rac.mutation.SetAddress(s)
	return rac
}

// SetAccountIndex sets the "accountIndex" field.
func (rac *ReceiveAddressCreate) SetAccountIndex(i int) *ReceiveAddressCreate {
	rac.mutation.SetAccountIndex(i)
	return rac
}

// SetStatus sets the "status" field.
func (rac *ReceiveAddressCreate) SetStatus(r receiveaddress.Status) *ReceiveAddressCreate {
	rac.mutation.SetStatus(r)
	return rac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rac *ReceiveAddressCreate) SetNillableStatus(r *receiveaddress.Status) *ReceiveAddressCreate {
	if r != nil {
		rac.SetStatus(*r)
	}
	return rac
}

// SetLastUsed sets the "last_used" field.
func (rac *ReceiveAddressCreate) SetLastUsed(t time.Time) *ReceiveAddressCreate {
	rac.mutation.SetLastUsed(t)
	return rac
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (rac *ReceiveAddressCreate) SetNillableLastUsed(t *time.Time) *ReceiveAddressCreate {
	if t != nil {
		rac.SetLastUsed(*t)
	}
	return rac
}

// Mutation returns the ReceiveAddressMutation object of the builder.
func (rac *ReceiveAddressCreate) Mutation() *ReceiveAddressMutation {
	return rac.mutation
}

// Save creates the ReceiveAddress in the database.
func (rac *ReceiveAddressCreate) Save(ctx context.Context) (*ReceiveAddress, error) {
	rac.defaults()
	return withHooks(ctx, rac.sqlSave, rac.mutation, rac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rac *ReceiveAddressCreate) SaveX(ctx context.Context) *ReceiveAddress {
	v, err := rac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rac *ReceiveAddressCreate) Exec(ctx context.Context) error {
	_, err := rac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rac *ReceiveAddressCreate) ExecX(ctx context.Context) {
	if err := rac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rac *ReceiveAddressCreate) defaults() {
	if _, ok := rac.mutation.CreatedAt(); !ok {
		v := receiveaddress.DefaultCreatedAt()
		rac.mutation.SetCreatedAt(v)
	}
	if _, ok := rac.mutation.UpdatedAt(); !ok {
		v := receiveaddress.DefaultUpdatedAt()
		rac.mutation.SetUpdatedAt(v)
	}
	if _, ok := rac.mutation.Status(); !ok {
		v := receiveaddress.DefaultStatus
		rac.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rac *ReceiveAddressCreate) check() error {
	if _, ok := rac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReceiveAddress.created_at"`)}
	}
	if _, ok := rac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReceiveAddress.updated_at"`)}
	}
	if _, ok := rac.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "ReceiveAddress.address"`)}
	}
	if _, ok := rac.mutation.AccountIndex(); !ok {
		return &ValidationError{Name: "accountIndex", err: errors.New(`ent: missing required field "ReceiveAddress.accountIndex"`)}
	}
	if _, ok := rac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReceiveAddress.status"`)}
	}
	if v, ok := rac.mutation.Status(); ok {
		if err := receiveaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReceiveAddress.status": %w`, err)}
		}
	}
	return nil
}

func (rac *ReceiveAddressCreate) sqlSave(ctx context.Context) (*ReceiveAddress, error) {
	if err := rac.check(); err != nil {
		return nil, err
	}
	_node, _spec := rac.createSpec()
	if err := sqlgraph.CreateNode(ctx, rac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rac.mutation.id = &_node.ID
	rac.mutation.done = true
	return _node, nil
}

func (rac *ReceiveAddressCreate) createSpec() (*ReceiveAddress, *sqlgraph.CreateSpec) {
	var (
		_node = &ReceiveAddress{config: rac.config}
		_spec = sqlgraph.NewCreateSpec(receiveaddress.Table, sqlgraph.NewFieldSpec(receiveaddress.FieldID, field.TypeInt))
	)
	if value, ok := rac.mutation.CreatedAt(); ok {
		_spec.SetField(receiveaddress.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rac.mutation.UpdatedAt(); ok {
		_spec.SetField(receiveaddress.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rac.mutation.Address(); ok {
		_spec.SetField(receiveaddress.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := rac.mutation.AccountIndex(); ok {
		_spec.SetField(receiveaddress.FieldAccountIndex, field.TypeInt, value)
		_node.AccountIndex = value
	}
	if value, ok := rac.mutation.Status(); ok {
		_spec.SetField(receiveaddress.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rac.mutation.LastUsed(); ok {
		_spec.SetField(receiveaddress.FieldLastUsed, field.TypeTime, value)
		_node.LastUsed = value
	}
	return _node, _spec
}

// ReceiveAddressCreateBulk is the builder for creating many ReceiveAddress entities in bulk.
type ReceiveAddressCreateBulk struct {
	config
	builders []*ReceiveAddressCreate
}

// Save creates the ReceiveAddress entities in the database.
func (racb *ReceiveAddressCreateBulk) Save(ctx context.Context) ([]*ReceiveAddress, error) {
	specs := make([]*sqlgraph.CreateSpec, len(racb.builders))
	nodes := make([]*ReceiveAddress, len(racb.builders))
	mutators := make([]Mutator, len(racb.builders))
	for i := range racb.builders {
		func(i int, root context.Context) {
			builder := racb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReceiveAddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, racb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, racb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, racb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (racb *ReceiveAddressCreateBulk) SaveX(ctx context.Context) []*ReceiveAddress {
	v, err := racb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (racb *ReceiveAddressCreateBulk) Exec(ctx context.Context) error {
	_, err := racb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (racb *ReceiveAddressCreateBulk) ExecX(ctx context.Context) {
	if err := racb.Exec(ctx); err != nil {
		panic(err)
	}
}
