// Code generated by ent, DO NOT EDIT.

package transactionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/paycrest/protocol/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldID, id))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSenderID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldProviderID, v))
}

// GatewayID applies equality check predicate on the "gateway_id" field. It's identical to GatewayIDEQ.
func GatewayID(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldGatewayID, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldNetwork, v))
}

// TransactionHash applies equality check predicate on the "transaction_hash" field. It's identical to TransactionHashEQ.
func TransactionHash(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldTransactionHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldSenderID, v))
}

// SenderIDContains applies the Contains predicate on the "sender_id" field.
func SenderIDContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldSenderID, v))
}

// SenderIDHasPrefix applies the HasPrefix predicate on the "sender_id" field.
func SenderIDHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldSenderID, v))
}

// SenderIDHasSuffix applies the HasSuffix predicate on the "sender_id" field.
func SenderIDHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldSenderID, v))
}

// SenderIDIsNil applies the IsNil predicate on the "sender_id" field.
func SenderIDIsNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIsNull(FieldSenderID))
}

// SenderIDNotNil applies the NotNil predicate on the "sender_id" field.
func SenderIDNotNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotNull(FieldSenderID))
}

// SenderIDEqualFold applies the EqualFold predicate on the "sender_id" field.
func SenderIDEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldSenderID, v))
}

// SenderIDContainsFold applies the ContainsFold predicate on the "sender_id" field.
func SenderIDContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldSenderID, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldProviderID, v))
}

// ProviderIDContains applies the Contains predicate on the "provider_id" field.
func ProviderIDContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldProviderID, v))
}

// ProviderIDHasPrefix applies the HasPrefix predicate on the "provider_id" field.
func ProviderIDHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldProviderID, v))
}

// ProviderIDHasSuffix applies the HasSuffix predicate on the "provider_id" field.
func ProviderIDHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldProviderID, v))
}

// ProviderIDIsNil applies the IsNil predicate on the "provider_id" field.
func ProviderIDIsNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIsNull(FieldProviderID))
}

// ProviderIDNotNil applies the NotNil predicate on the "provider_id" field.
func ProviderIDNotNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotNull(FieldProviderID))
}

// ProviderIDEqualFold applies the EqualFold predicate on the "provider_id" field.
func ProviderIDEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldProviderID, v))
}

// ProviderIDContainsFold applies the ContainsFold predicate on the "provider_id" field.
func ProviderIDContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldProviderID, v))
}

// GatewayIDEQ applies the EQ predicate on the "gateway_id" field.
func GatewayIDEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldGatewayID, v))
}

// GatewayIDNEQ applies the NEQ predicate on the "gateway_id" field.
func GatewayIDNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldGatewayID, v))
}

// GatewayIDIn applies the In predicate on the "gateway_id" field.
func GatewayIDIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldGatewayID, vs...))
}

// GatewayIDNotIn applies the NotIn predicate on the "gateway_id" field.
func GatewayIDNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldGatewayID, vs...))
}

// GatewayIDGT applies the GT predicate on the "gateway_id" field.
func GatewayIDGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldGatewayID, v))
}

// GatewayIDGTE applies the GTE predicate on the "gateway_id" field.
func GatewayIDGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldGatewayID, v))
}

// GatewayIDLT applies the LT predicate on the "gateway_id" field.
func GatewayIDLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldGatewayID, v))
}

// GatewayIDLTE applies the LTE predicate on the "gateway_id" field.
func GatewayIDLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldGatewayID, v))
}

// GatewayIDContains applies the Contains predicate on the "gateway_id" field.
func GatewayIDContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldGatewayID, v))
}

// GatewayIDHasPrefix applies the HasPrefix predicate on the "gateway_id" field.
func GatewayIDHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldGatewayID, v))
}

// GatewayIDHasSuffix applies the HasSuffix predicate on the "gateway_id" field.
func GatewayIDHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldGatewayID, v))
}

// GatewayIDIsNil applies the IsNil predicate on the "gateway_id" field.
func GatewayIDIsNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIsNull(FieldGatewayID))
}

// GatewayIDNotNil applies the NotNil predicate on the "gateway_id" field.
func GatewayIDNotNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotNull(FieldGatewayID))
}

// GatewayIDEqualFold applies the EqualFold predicate on the "gateway_id" field.
func GatewayIDEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldGatewayID, v))
}

// GatewayIDContainsFold applies the ContainsFold predicate on the "gateway_id" field.
func GatewayIDContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldGatewayID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldStatus, vs...))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkIsNil applies the IsNil predicate on the "network" field.
func NetworkIsNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIsNull(FieldNetwork))
}

// NetworkNotNil applies the NotNil predicate on the "network" field.
func NetworkNotNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotNull(FieldNetwork))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldNetwork, v))
}

// TransactionHashEQ applies the EQ predicate on the "transaction_hash" field.
func TransactionHashEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldTransactionHash, v))
}

// TransactionHashNEQ applies the NEQ predicate on the "transaction_hash" field.
func TransactionHashNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldTransactionHash, v))
}

// TransactionHashIn applies the In predicate on the "transaction_hash" field.
func TransactionHashIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldTransactionHash, vs...))
}

// TransactionHashNotIn applies the NotIn predicate on the "transaction_hash" field.
func TransactionHashNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldTransactionHash, vs...))
}

// TransactionHashGT applies the GT predicate on the "transaction_hash" field.
func TransactionHashGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldTransactionHash, v))
}

// TransactionHashGTE applies the GTE predicate on the "transaction_hash" field.
func TransactionHashGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldTransactionHash, v))
}

// TransactionHashLT applies the LT predicate on the "transaction_hash" field.
func TransactionHashLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldTransactionHash, v))
}

// TransactionHashLTE applies the LTE predicate on the "transaction_hash" field.
func TransactionHashLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldTransactionHash, v))
}

// TransactionHashContains applies the Contains predicate on the "transaction_hash" field.
func TransactionHashContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldTransactionHash, v))
}

// TransactionHashHasPrefix applies the HasPrefix predicate on the "transaction_hash" field.
func TransactionHashHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldTransactionHash, v))
}

// TransactionHashHasSuffix applies the HasSuffix predicate on the "transaction_hash" field.
func TransactionHashHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldTransactionHash, v))
}

// TransactionHashIsNil applies the IsNil predicate on the "transaction_hash" field.
func TransactionHashIsNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIsNull(FieldTransactionHash))
}

// TransactionHashNotNil applies the NotNil predicate on the "transaction_hash" field.
func TransactionHashNotNil() predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotNull(FieldTransactionHash))
}

// TransactionHashEqualFold applies the EqualFold predicate on the "transaction_hash" field.
func TransactionHashEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldTransactionHash, v))
}

// TransactionHashContainsFold applies the ContainsFold predicate on the "transaction_hash" field.
func TransactionHashContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldTransactionHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(func(s *sql.Selector) {
		p(s.Not())
	})
}
