-- Modify "institutions" table
ALTER TABLE "institutions" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1;
-- Modify "linked_addresses" table
ALTER TABLE "linked_addresses" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Rename an index from "lockpaymentorder_gateway_id_ra_65d1cd4f9b7a0ff4525b6f2bc506afdc" to "lockpaymentorder_gateway_id_rate_tx_hash_block_number_instituti"
ALTER INDEX "lockpaymentorder_gateway_id_ra_65d1cd4f9b7a0ff4525b6f2bc506afdc" RENAME TO "lockpaymentorder_gateway_id_rate_tx_hash_block_number_instituti";
-- Modify "networks" table
ALTER TABLE "networks" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART, ADD COLUMN "bundler_url" character varying NULL, ADD COLUMN "paymaster_url" character varying NULL;
-- Modify "payment_order_recipients" table
ALTER TABLE "payment_order_recipients" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "provider_order_tokens" table
ALTER TABLE "provider_order_tokens" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "provider_ratings" table
ALTER TABLE "provider_ratings" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "provision_buckets" table
ALTER TABLE "provision_buckets" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "receive_addresses" table
ALTER TABLE "receive_addresses" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "sender_order_tokens" table
ALTER TABLE "sender_order_tokens" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Rename an index from "senderordertoken_sender_profil_c0e12093989225f7a56a29b8ff69c3bf" to "senderordertoken_sender_profile_order_tokens_token_sender_setti"
ALTER INDEX "senderordertoken_sender_profil_c0e12093989225f7a56a29b8ff69c3bf" RENAME TO "senderordertoken_sender_profile_order_tokens_token_sender_setti";
-- Modify "tokens" table
ALTER TABLE "tokens" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Modify "webhook_retry_attempts" table
ALTER TABLE "webhook_retry_attempts" ALTER COLUMN "id" SET GENERATED BY DEFAULT SET START WITH 1 SET INCREMENT BY 1 RESTART;
-- Drop "ent_types" table
DROP TABLE "ent_types";
