// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// FiatCurrency is the predicate function for fiatcurrency builders.
type FiatCurrency func(*sql.Selector)

// LockOrderFulfillment is the predicate function for lockorderfulfillment builders.
type LockOrderFulfillment func(*sql.Selector)

// LockPaymentOrder is the predicate function for lockpaymentorder builders.
type LockPaymentOrder func(*sql.Selector)

// Network is the predicate function for network builders.
type Network func(*sql.Selector)

// PaymentOrder is the predicate function for paymentorder builders.
type PaymentOrder func(*sql.Selector)

// PaymentOrderRecipient is the predicate function for paymentorderrecipient builders.
type PaymentOrderRecipient func(*sql.Selector)

// ProviderAvailability is the predicate function for provideravailability builders.
type ProviderAvailability func(*sql.Selector)

// ProviderOrderToken is the predicate function for providerordertoken builders.
type ProviderOrderToken func(*sql.Selector)

// ProviderOrderTokenAddress is the predicate function for providerordertokenaddress builders.
type ProviderOrderTokenAddress func(*sql.Selector)

// ProviderProfile is the predicate function for providerprofile builders.
type ProviderProfile func(*sql.Selector)

// ProviderRating is the predicate function for providerrating builders.
type ProviderRating func(*sql.Selector)

// ProvisionBucket is the predicate function for provisionbucket builders.
type ProvisionBucket func(*sql.Selector)

// ReceiveAddress is the predicate function for receiveaddress builders.
type ReceiveAddress func(*sql.Selector)

// SenderProfile is the predicate function for senderprofile builders.
type SenderProfile func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// ValidatorProfile is the predicate function for validatorprofile builders.
type ValidatorProfile func(*sql.Selector)

// VerificationToken is the predicate function for verificationtoken builders.
type VerificationToken func(*sql.Selector)
